version: "3"

services:
  backend:
    build: .
    container_name: typescript
    command: sh docker-entrypoint.sh
    ports:
      - $MACHINE_PORT:$DOCKER_PORT
    restart: always
    environment:
      JWT_SECRET: $JWT_SECRET
      MONGO_USER: $MONGO_USER
      MONGO_PASSWORD: $MONGO_PASSWORD
      MONGO_PATH: $MONGO_PATH
      PORT: $DOCKER_PORT